### ISSUE TITLE
Using with requirejs

### ISSUE THREAD

**Issue by JeffB1** [poelstra/ts-promise#10]
I really want to use this library as it seems to be one of the more complete typescript promises library. However, I can't get it working in my project. I am using requirejs with TypeScript 1.8.5 in Visual Studio 2013. I've added the promise to the require.config

```
'ts-promise': ['node_modules/ts-promise/dist/lib/Promise', 'node_modules/ts-promise/dist/lib/async', 'node_modules/ts-promise/dist/lib/util',
            'node_modules/ts-promise/dist/lib/Trace', 'node_modules/ts-promise/dist/lib/BaseError']
```
Note I did have it originally with just the first path but tried to specific multiple paths like this in the hope that it would fix the problem.

But it fails in promises.ts :

```
import async from "./async";   <------- fails here
import { assert } from "./util";
import Trace from "./Trace";
import BaseError from "./BaseError";

```
With the error:
`Module name "async" has not been loaded yet for context: _. Use require([])`

I am new to TypeScrript and am loving it. Its support for classes and type checking has saved me on a number of occasions. But getting third party libraries like this is killing me (this is not the first requirejs issue I've had!! )

My understanding is that commonjs should only be used on server where using node.js and on browser should use AMD with requirejs. Is that your experience (as I said, I:m new to typescript!) So how come so many third party libraries have issue with requirejs? I feel like I'm missing something as it shouldn't be this hard.

**Comment by poelstra** [comment]
Hey Jeff,

I don't have experience with `requirejs` (or AMD) myself. For use in the browser, I've been using `browserify` (or `webpack`) instead. Using `browserify` makes it very easy to use CommonJS modules in the browser.

If you're indeed mainly using `npm` for installing your modules, you're basically living in CommonJS land, and using `browserify` or `webpack` is likely your best bet for converting code to run in the browser.

**Comment by poelstra** [comment]
For reference, a minified UMD browser bundle is included in `dist/browser.min.js` since 0.3.1, and referenced from `package.json`.
