### ISSUE TITLE
Extending built-ins like Error, Array, and Map may no longer work

### ISSUE THREAD

**Issue by mgroenhoff** [poelstra/ts-promise#14]
This is just a heads up because `BaseError` extends `Error`: https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#extending-built-ins-like-error-array-and-map-may-no-longer-work

**Comment by poelstra** [comment]
Interesting. First, they actually fixed extending these, now they break it again. Have to think a bit how to best solve this, their recommendation still seems quite dirty.

Thanks for the heads up!

**Comment by poelstra** [comment]
Fixed in 1.0.0, thanks!
